matrix:
  include:
    - name: linux-py36
      language: python
      python: 3.6
      sudo: required
      services:
        - docker
install:
  - python -m pip install -U pip

script:
  - mkdir build
  - cd build
  - cmake -GNinja -DVTK_WRAP_PYTHON=ON -DVTK_BUILD_TESTING=WANT ..
  - ctest -n
  - ctest
